<?php

/**
 * WidgetCarousel - A customizable Carousel.
 *
 *
 */

class WidgetCarousel extends Widget implements Module {

  /**
   * getModuleInfo is a module required by all modules to tell ProcessWire about them
   *
   * @return array
   *
   */
  public static function getModuleInfo() {
    return array(
      'title' => 'Widget Carousel', 
      'version' => 001, 
      'summary' => _('A customizable Carousel.'),
      'icon' => 'cubes',
      'requires' => array('Widgets')
      );
  }

  public static function getDefaultSettings()
  {
    return array(
      'image_field' => 'images',
      'image_count' => 1,
      'image_thumbnail' => '',
      'image_width' => null,
      'image_height' => null,
      'include_text' => 1,
      'single_text' => 1,
      'text_from_description' => 1,
      'text_field' => 'headline'
      );
  }

  protected function getFieldOptions($type = '')
  {
    $arr = array();
    foreach ($this->fields as $field) {
      if (!$type) $arr[$field->name] = $field->get('labal|name');
      else if ($type === (string) $field->type) $arr[$field->name] = $field->get('label|name');
    }
    return $arr;
  }

  public function setArray(array $arr)
  {
    parent::setArray($arr);
    $settings = array_merge(self::getDefaultSettings(), $this->settings->getArray());
    $this->settings->setArray($settings);
  }

  public function getSettingsFields($multipleRenders = true)
  {
    $fields = parent::getSettingsFields($multipleRenders);

    $field = $this->modules->get('InputfieldSelect');
    $field->name = 'image_field';
    $field->label = $this->_('Image Field');
    $field->attr('value', $this->settings->image_field);
    $field->addOptions($this->getFieldOptions());
    $field->required = true;
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'image_count';
    $field->label = $this->_('Image Count');
    $field->attr('value', $this->settings->image_count);
    $field->description = $this->_('How many images from each page should be taken?');
    $field->required = true;
    $fields->add($field);

    $field = $this->modules->get('InputfieldText');
    $field->name = 'image_thumbnail';
    $field->label = $this->_('Image Thumbnail');
    $field->attr('value', $this->settings->image_thumbnail);
    $field->description = $this->_('Write the name of the thumbnail that will be retrieved for image slide.');
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'image_width';
    $field->label = $this->_('Image Width');
    $field->attr('value', $this->settings->image_width);
    $field->description = $this->_('The width of the image.');
    $field->showIf = "image_thumbnail=''";
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'image_height';
    $field->label = $this->_('Image Height');
    $field->attr('value', $this->settings->image_height);
    $field->description = $this->_('The height of the image');
    $field->showIf = "image_thumbnail=''";
    $fields->add($field);

    $field = $this->modules->get('InputfieldCheckbox');
    $field->name = 'include_text';
    $field->label = $this->_('Include Text');
    $field->attr('checked', $this->settings->include_text);
    $field->description = $this->_('Check this if you want to include text on your Carousel.');
    $fields->add($field);

    $field = $this->modules->get('InputfieldCheckbox');
    $field->name = 'single_text';
    $field->label = $this->_('Single Text');
    $field->attr('checked', $this->settings->single_text);
    $field->description = $this->_('Show only one text for all slides. Uncheck this if you want to have seperate text for each image slide.');
    $field->showIf = "include_text=1";
    $fields->add($field);

    $field = $this->modules->get('InputfieldCheckbox');
    $field->name = 'text_from_description';
    $field->label = $this->_('Text From Description');
    $field->attr('checked', $this->settings->text_from_description);
    $field->description = $this->_('Check this if you want the text of the slides be taken from their descriptions.');
    $field->showIf = "include_text=1, single_text=0";
    $fields->add($field);

    $field = $this->modules->get('InputfieldSelect');
    $field->name = 'text_field';
    $field->label = $this->_('Text Field');
    $field->attr('value', $this->settings->text_field);
    $field->description = $this->_('Choose the field where from the text will be used.');
    $field->addOptions($this->getFieldOptions());
    $field->required = true;
    $field->showIf = "include_text=1, text_from_description=0";
    $field->requiredIf = "text_from_description=0";
    $fields->add($field);

    return $fields;
  }

  public function processSettingsFields(InputfieldWrapper $settings)
  {
    parent::processSettingsFields($settings);
      
    $this->settings->image_field = $settings->get('image_field')->value;
    $this->settings->image_count = $settings->get('image_count')->value;
    $this->settings->image_thumbnail = $settings->get('image_thumbnail')->value;
    $this->settings->image_width = $settings->get('image_width')->value;
    $this->settings->image_height = $settings->get('image_height')->value;
    $this->settings->include_text = $settings->get('include_text')->value;
    $this->settings->single_text = $settings->get('single_text')->value;
    $this->settings->text_from_description = $settings->get('text_from_description')->value;
    $this->settings->text_field = $settings->get('text_field')->value;
  }
}
