<?php

/**
 * WidgetCarousel - A customizable Carousel.
 *
 *
 */

class WidgetCarousel extends Widget implements Module {

  /**
   * getModuleInfo is a module required by all modules to tell ProcessWire about them
   *
   * @return array
   *
   */
  public static function getModuleInfo() {
    return array(
      'title' => 'Widget Carousel', 
      'version' => 001, 
      'summary' => _('A customizable Carousel.'),
      'icon' => 'cubes',
      'requires' => array('Widgets')
      );
  }

  public static function getDefaultSettings()
  {
    return array(
      'image_field' => 'images',
      'image_count' => 1,
      'image_thumbnail' => '',
      'image_width' => null,
      'image_height' => null,
      'include_text' => 1,
      'single_text' => 1,
      'text_from_description' => 0,
      'text_field' => 'headline|title',
      'animation_type' => 'slide',
      'speed' => 1000,
      'interval' => 7000
      );
  }

  protected function getFieldOptions($type = '')
  {
    $arr = array();
    foreach ($this->fields as $field) {
      if (!$type) $arr[$field->name] = $field->get('labal|name');
      else if ($type === (string) $field->type) $arr[$field->name] = $field->get('label|name');
    }
    return $arr;
  }

  protected function getAnimationOptions()
  {
    return array(
      'slide' => $this->_('Slide'),
      'fade' => $this->_('Fade')
      );
  }

  public function setArray(array $arr)
  {
    parent::setArray($arr);
    $settings = array_merge(self::getDefaultSettings(), $this->settings->getArray());
    $this->settings->setArray($settings);
  }

  public function getSettingsFields($multipleRenders = true)
  {
    $fields = parent::getSettingsFields($multipleRenders);

    $field = $this->modules->get('InputfieldSelect');
    $field->name = 'image_field';
    $field->label = $this->_('Image Field');
    $field->attr('value', $this->settings->image_field);
    $field->addOptions($this->getFieldOptions());
    $field->required = true;
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'image_count';
    $field->label = $this->_('Image Count');
    $field->attr('value', $this->settings->image_count);
    $field->description = $this->_('How many images from each page should be taken?');
    $field->required = true;
    $fields->add($field);

    $field = $this->modules->get('InputfieldText');
    $field->name = 'image_thumbnail';
    $field->label = $this->_('Image Thumbnail');
    $field->attr('value', $this->settings->image_thumbnail);
    $field->description = $this->_('Write the name of the thumbnail that will be retrieved for image slide.');
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'image_width';
    $field->label = $this->_('Image Width');
    $field->attr('value', $this->settings->image_width);
    $field->description = $this->_('The width of the image.');
    $field->showIf = "image_thumbnail=''";
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'image_height';
    $field->label = $this->_('Image Height');
    $field->attr('value', $this->settings->image_height);
    $field->description = $this->_('The height of the image');
    $field->showIf = "image_thumbnail=''";
    $fields->add($field);

    $field = $this->modules->get('InputfieldCheckbox');
    $field->name = 'include_text';
    $field->label = $this->_('Include Text');
    $field->attr('checked', $this->settings->include_text);
    $field->description = $this->_('Check this if you want to include text on your Carousel.');
    $fields->add($field);

    $field = $this->modules->get('InputfieldCheckbox');
    $field->name = 'single_text';
    $field->label = $this->_('Single Text');
    $field->attr('checked', $this->settings->single_text);
    $field->description = $this->_('Show only one text for all slides. Uncheck this if you want to have seperate text for each image slide.');
    $field->showIf = "include_text=1";
    $fields->add($field);

    $field = $this->modules->get('InputfieldCheckbox');
    $field->name = 'text_from_description';
    $field->label = $this->_('Text From Description');
    $field->attr('checked', $this->settings->text_from_description);
    $field->description = $this->_('Check this if you want the text of the slides be taken from their descriptions.');
    $field->showIf = "include_text=1, single_text=0";
    $fields->add($field);

    $field = $this->modules->get('InputfieldText');
    $field->name = 'text_field';
    $field->label = $this->_('Text Field');
    $field->attr('value', $this->settings->text_field);
    $field->description = $this->_('Choose the field where from the text will be used.');
    $field->notes = $this->_('You can set combined fields like `headline|title`');
    $field->showIf = "include_text=1";
    $fields->add($field);

    $field = $this->modules->get('InputfieldSelect');
    $field->name = 'animation_type';
    $field->label = $this->_('Animation Type');
    $field->attr('value', $this->settings->animation_type);
    $field->addOptions($this->getAnimationOptions());
    $field->required = true;
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'speed';
    $field->label = $this->_('Animation Speed');
    $field->attr('value', $this->settings->speed);
    $fields->add($field);

    $field = $this->modules->get('InputfieldInteger');
    $field->name = 'interval';
    $field->label = $this->_('Animation Interval');
    $field->attr('value', $this->settings->interval);
    $fields->add($field);    

    return $fields;
  }

  public function processSettingsFields(InputfieldWrapper $settings)
  {
    parent::processSettingsFields($settings);

    foreach (self::getDefaultSettings() as $key => $value) {
      $this->settings->set($key, $settings->get($key)->value);
    }
  }
}
